server:
  port: 8080
  tomcat:
    uri-encoding: utf-8
spring:
  profiles:
    active: dev
mybatis:
  configuration:
    map-underscore-to-camel-case: true
  config-location: mybatis/mybatis-config.xml
  mapper-locations: mybatis/mapper/**/*.xml